name: tesla
description: "Control and monitor Tesla Products"
version: 0.1.1+1
homepage: "https://github.com/SpinlockLabs/tesla.dart"
authors:
- "Kenneth Endfinger <kaendfinger@gmail.com>"
environment:
  sdk: ">=1.17.0 <3.0.0"
